foreach(option --startup-delay --char-delay)
    foreach(value -1 4294967296 abc 12ms "")
        execute_process(COMMAND "${RDK_EXE}" "${option}" "${value}"
            RESULT_VARIABLE result OUTPUT_VARIABLE output ERROR_VARIABLE error)
        if(NOT result EQUAL 1 OR NOT error MATCHES "requires an integer")
            message(FATAL_ERROR "${option} '${value}': result=${result}, ${output}${error}")
        endif()
    endforeach()
endforeach()

foreach(option --startup-delay --char-delay --text --input)
    execute_process(COMMAND "${RDK_EXE}" "${option}"
        RESULT_VARIABLE result OUTPUT_VARIABLE output ERROR_VARIABLE error)
    if(NOT result EQUAL 1 OR NOT error MATCHES "requires a value")
        message(FATAL_ERROR "${option}: result=${result}, ${output}${error}")
    endif()
endforeach()

execute_process(COMMAND "${RDK_EXE}" --startup-delay 0 --char-delay 4294967295 /help
    RESULT_VARIABLE result OUTPUT_VARIABLE output ERROR_VARIABLE error)
if(NOT result EQUAL 0)
    message(FATAL_ERROR "Valid delay boundaries: result=${result}, ${output}${error}")
endif()
if(NOT output MATCHES "Ctrl[+]Shift[+]F10" OR NOT output MATCHES "Ctrl[+]Shift[+]F11" OR
   NOT output MATCHES "Ctrl[+]Shift[+]F12")
    message(FATAL_ERROR "Help must list local minimize, reconnect, and quit shortcuts: ${output}")
endif()
foreach(option /screen:1,2 /monitors:1,2)
    execute_process(COMMAND "${RDK_EXE}" "${option}" /list:monitor
        RESULT_VARIABLE result OUTPUT_VARIABLE output ERROR_VARIABLE error)
    if(NOT result EQUAL 0 OR NOT output MATCHES "[1-9][0-9]*: [0-9]+x[0-9]+ at")
        message(FATAL_ERROR "Monitor listing with ${option}: result=${result}, ${output}${error}")
    endif()
endforeach()
foreach(option /screen: /screen:abc /screen:-1 /monitors:abc)
    execute_process(COMMAND "${RDK_EXE}" "${option}"
        RESULT_VARIABLE result OUTPUT_VARIABLE output ERROR_VARIABLE error)
    if(NOT result EQUAL 1)
        message(FATAL_ERROR "Invalid monitor selection ${option}: result=${result}, ${output}${error}")
    endif()
endforeach()
foreach(sequence "<delay><enter><F1>" "<ESC><tab>hello<<world>" "<delay><delay><enter>" "")
    execute_process(COMMAND "${RDK_EXE}" --input "${sequence}" /help
        RESULT_VARIABLE result OUTPUT_VARIABLE output ERROR_VARIABLE error)
    if(NOT result EQUAL 0)
        message(FATAL_ERROR "Valid startup sequence: result=${result}, ${output}${error}")
    endif()
endforeach()
foreach(sequence "<unknown>" "abc<enter" "<delay:1000>" "<F13>" "<>")
    execute_process(COMMAND "${RDK_EXE}" --input "${sequence}"
        RESULT_VARIABLE result OUTPUT_VARIABLE output ERROR_VARIABLE error)
    if(NOT result EQUAL 1 OR NOT error MATCHES "invalid /input")
        message(FATAL_ERROR "Invalid startup sequence: result=${result}, ${output}${error}")
    endif()
endforeach()
foreach(first --text --input)
    if(first STREQUAL "--text")
        set(second --input)
    else()
        set(second --text)
    endif()
    execute_process(COMMAND "${RDK_EXE}" "${first}" "hello" "${second}" "<enter>"
        RESULT_VARIABLE result OUTPUT_VARIABLE output ERROR_VARIABLE error)
    if(NOT result EQUAL 1 OR NOT error MATCHES "cannot be combined")
        message(FATAL_ERROR "Conflicting startup options: result=${result}, ${output}${error}")
    endif()
endforeach()
execute_process(COMMAND "${RDK_EXE}" --text "<unknown>" /help
    RESULT_VARIABLE result OUTPUT_VARIABLE output ERROR_VARIABLE error)
if(NOT result EQUAL 0)
    message(FATAL_ERROR "Literal --text compatibility: result=${result}, ${output}${error}")
endif()
message(STATUS "Passed CLI validation checks")
execute_process(COMMAND "${RDK_EXE}" /camera /microphone /sound /help
    RESULT_VARIABLE result OUTPUT_VARIABLE output ERROR_VARIABLE error)
if(NOT result EQUAL 0)
    message(FATAL_ERROR "Camera/audio option parsing: result=${result}, ${output}${error}")
endif()
execute_process(COMMAND "${RDK_EXE}" /list:camera
    RESULT_VARIABLE result OUTPUT_VARIABLE output ERROR_VARIABLE error)
if(NOT result EQUAL 0 OR NOT output MATCHES "Camera:|No local cameras found")
    message(FATAL_ERROR "Camera metadata listing: result=${result}, ${output}${error}")
endif()
foreach(option /list:microphone /LIST:MICROPHONE)
    execute_process(COMMAND "${RDK_EXE}" "${option}" /list:camera
        RESULT_VARIABLE result OUTPUT_VARIABLE output ERROR_VARIABLE error)
    if(NOT result EQUAL 0 OR NOT output MATCHES "local microphones" OR
       NOT output MATCHES "WinMM recording devices:" OR NOT output MATCHES "Camera:|No local cameras found")
        message(FATAL_ERROR "Microphone/camera metadata listing: result=${result}, ${output}${error}")
    endif()
endforeach()
foreach(option /clipboard /clipboard:direction-to:local,files-to:local /clipboard:files-to:off +clipboard -clipboard)
    execute_process(COMMAND "${RDK_EXE}" "${option}" /help
        RESULT_VARIABLE result OUTPUT_VARIABLE output ERROR_VARIABLE error)
    if(NOT result EQUAL 0)
        message(FATAL_ERROR "Clipboard option ${option}: result=${result}, ${output}${error}")
    endif()
endforeach()

foreach(option /startup-delay /char-delay)
    foreach(value -1 4294967296 abc 12ms "")
        execute_process(COMMAND "${RDK_EXE}" "${option}:${value}"
            RESULT_VARIABLE result OUTPUT_VARIABLE output ERROR_VARIABLE error)
        if(NOT result EQUAL 1 OR NOT error MATCHES "requires an integer")
            message(FATAL_ERROR "${option}:${value}: result=${result}, ${output}${error}")
        endif()
    endforeach()
endforeach()
foreach(option /startup-delay /char-delay /text /input)
    execute_process(COMMAND "${RDK_EXE}" "${option}" /help
        RESULT_VARIABLE result OUTPUT_VARIABLE output ERROR_VARIABLE error)
    if(NOT result EQUAL 1 OR NOT error MATCHES "requires a value")
        message(FATAL_ERROR "Missing colon value ${option}: result=${result}, ${output}${error}")
    endif()
endforeach()
foreach(option "/input:<delay><enter><F1>" "/INPUT:<ESC>hello world: value" "/input:"
        "/text:<unknown>: hello world" "/text:" /credentials /CREDENTIALS --credentials)
    execute_process(COMMAND "${RDK_EXE}" "${option}" /startup-delay:0 /char-delay:4294967295 /help
        RESULT_VARIABLE result OUTPUT_VARIABLE output ERROR_VARIABLE error)
    if(NOT result EQUAL 0 OR NOT output MATCHES "/input:SEQUENCE" OR NOT output MATCHES "/credentials")
        message(FATAL_ERROR "Slash option ${option}: result=${result}, ${output}${error}")
    endif()
endforeach()
foreach(sequence "<unknown>" "abc<enter" "<delay:1000>" "<F13>" "<>" "hello world:<unknown>")
    execute_process(COMMAND "${RDK_EXE}" "/input:${sequence}"
        RESULT_VARIABLE result OUTPUT_VARIABLE output ERROR_VARIABLE error)
    if(NOT result EQUAL 1 OR NOT error MATCHES "invalid /input")
        message(FATAL_ERROR "Invalid slash sequence: result=${result}, ${output}${error}")
    endif()
endforeach()
foreach(option /input:hello /text:hello)
    if(option STREQUAL "/input:hello")
        set(other /text:hello)
        set(legacy --text)
    else()
        set(other /input:hello)
        set(legacy --input)
    endif()
    execute_process(COMMAND "${RDK_EXE}" "${option}" "${other}"
        RESULT_VARIABLE result OUTPUT_VARIABLE output ERROR_VARIABLE error)
    if(NOT result EQUAL 1 OR NOT error MATCHES "cannot be combined")
        message(FATAL_ERROR "Conflicting slash options: result=${result}, ${output}${error}")
    endif()
    execute_process(COMMAND "${RDK_EXE}" "${option}" "${legacy}" "hello"
        RESULT_VARIABLE result OUTPUT_VARIABLE output ERROR_VARIABLE error)
    if(NOT result EQUAL 1 OR NOT error MATCHES "cannot be combined")
        message(FATAL_ERROR "Conflicting mixed options: result=${result}, ${output}${error}")
    endif()
endforeach()